### ISSUE TITLE
execute electron:build to gen executable file, error occured

### ISSUE THREAD

**Issue by weixublog** [nashaofu/vue-cli-plugin-electron-builder-issue#1]
the webpack config

```
config.externals({ 'shortcut-capture': "require('shortcut-capture')" })
```

throw a error that cannot find module 'shortcut-capture'

**Comment by nashaofu** [comment]
因为执行打包之后dist_electron/bundled没有包含对应的node_modules导致的
![image](https://user-images.githubusercontent.com/19303058/83986310-eadbee00-a96e-11ea-9064-498e920cb244.png)
你应该要按照对应的配置去修改

**Comment by nashaofu** [comment]
配置修改为这个了
https://github.com/nashaofu/vue-cli-plugin-electron-builder-issue/blob/0f774a90b09e10b02f86fcb6b50645058fe1a4e8/vue.config.js#L1-L8
